# Generated by Django 5.0.1 on 2024-01-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNatura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='vto',
            field=models.DateField(),
        ),
    ]
